apiVersion: serverless.kyma-project.io/v1alpha1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: kyma-functions-orchestration-repo
  namespace: default
spec:
  url: https://github.com/kwiatekus/kyma-function-mixed.git

---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  creationTimestamp: null
  name: git-function-mixed
  namespace: default
spec:
  baseDir: /src/hello-world-function/
  reference: main
  runtime: nodejs14
  source: kyma-functions-orchestration-repo
  type: git

---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  creationTimestamp: null
  name: git-function-mixed
  namespace: default
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - handler: allow
    methods:
    - GET
    path: /.*
  service:
    host: hello
    name: git-function-mixed
    port: 80

